This notebook implements an English-language tweet sentiment classifier.we are going to get a goodaccuracy on the test data containing positive and negative sentiment tweets.Training and test data was downloaded from here : http://help.sentiment140.com/for-students/

In [46]:
#from matplotlib import pyplot as plt
#import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import classification_report

from sklearn.pipeline import Pipeline

In [47]:
# name out col's
columns = ['polarity', 'tweetid', 'date', 'query_name', 'user', 'text']

dftrain = pd.read_csv(r'datasets\trainingandtestdata\training.1600000.processed.noemoticon.csv',
                      header = None,
                      encoding ='ISO-8859-1')
dftest = pd.read_csv(r'datasets\trainingandtestdata\testdata.manual.2009.06.14.csv',
                     header = None,
                     encoding ='ISO-8859-1')
dftrain.columns = columns
dftest.columns = columns

dftrain

polarity     tweetid                          date query_name  \
0               0  1467810369  Mon Apr 06 22:19:45 PDT 2009   NO_QUERY   
1               0  1467810672  Mon Apr 06 22:19:49 PDT 2009   NO_QUERY   
2               0  1467810917  Mon Apr 06 22:19:53 PDT 2009   NO_QUERY   
3               0  1467811184  Mon Apr 06 22:19:57 PDT 2009   NO_QUERY   
4               0  1467811193  Mon Apr 06 22:19:57 PDT 2009   NO_QUERY   
5               0  1467811372  Mon Apr 06 22:20:00 PDT 2009   NO_QUERY   
6               0  1467811592  Mon Apr 06 22:20:03 PDT 2009   NO_QUERY   
7               0  1467811594  Mon Apr 06 22:20:03 PDT 2009   NO_QUERY   
8               0  1467811795  Mon Apr 06 22:20:05 PDT 2009   NO_QUERY   
9               0  1467812025  Mon Apr 06 22:20:09 PDT 2009   NO_QUERY   
10              0  1467812416  Mon Apr 06 22:20:16 PDT 2009   NO_QUERY   
11              0  1467812579  Mon Apr 06 22:20:17 PDT 2009   NO_QUERY   
12              0  1467812723  Mon Apr 06 22:20:19 PDT 2009   NO_QUERY   
13              0  1467812771  Mon Apr 06 22:20:19 PDT 2009   NO_QUERY   
14              0  1467812784  Mon Apr 06 22:20:20 PDT 2009   NO_QUERY   
15              0  1467812799  Mon Apr 06 22:20:20 PDT 2009   NO_QUERY   
16              0  1467812964  Mon Apr 06 22:20:22 PDT 2009   NO_QUERY   
17              0  1467813137  Mon Apr 06 22:20:25 PDT 2009   NO_QUERY   
18              0  1467813579  Mon Apr 06 22:20:31 PDT 2009   NO_QUERY   
19              0  1467813782  Mon Apr 06 22:20:34 PDT 2009   NO_QUERY   
20              0  1467813985  Mon Apr 06 22:20:37 PDT 2009   NO_QUERY   
21              0  1467813992  Mon Apr 06 22:20:38 PDT 2009   NO_QUERY   
22              0  1467814119  Mon Apr 06 22:20:40 PDT 2009   NO_QUERY   
23              0  1467814180  Mon Apr 06 22:20:40 PDT 2009   NO_QUERY   
24              0  1467814192  Mon Apr 06 22:20:41 PDT 2009   NO_QUERY   
25              0  1467814438  Mon Apr 06 22:20:44 PDT 2009   NO_QUERY   
26              0  1467814783  Mon Apr 06 22:20:50 PDT 2009   NO_QUERY   
27              0  1467814883  Mon Apr 06 22:20:52 PDT 2009   NO_QUERY   
28              0  1467815199  Mon Apr 06 22:20:56 PDT 2009   NO_QUERY   
29              0  1467815753  Mon Apr 06 22:21:04 PDT 2009   NO_QUERY   
...           ...         ...                           ...        ...   
1599970         4  2193578196  Tue Jun 16 08:38:54 PDT 2009   NO_QUERY   
1599971         4  2193578237  Tue Jun 16 08:38:54 PDT 2009   NO_QUERY   
1599972         4  2193578269  Tue Jun 16 08:38:54 PDT 2009   NO_QUERY   
1599973         4  2193578319  Tue Jun 16 08:38:55 PDT 2009   NO_QUERY   
1599974         4  2193578345  Tue Jun 16 08:38:55 PDT 2009   NO_QUERY   
1599975         4  2193578347  Tue Jun 16 08:38:55 PDT 2009   NO_QUERY   
1599976         4  2193578348  Tue Jun 16 08:38:55 PDT 2009   NO_QUERY   
1599977         4  2193578386  Tue Jun 16 08:38:55 PDT 2009   NO_QUERY   
1599978         4  2193578395  Tue Jun 16 08:38:55 PDT 2009   NO_QUERY   
1599979         4  2193578576  Tue Jun 16 08:38:57 PDT 2009   NO_QUERY   
1599980         4  2193578679  Tue Jun 16 08:38:56 PDT 2009   NO_QUERY   
1599981         4  2193578716  Tue Jun 16 08:38:57 PDT 2009   NO_QUERY   
1599982         4  2193578739  Tue Jun 16 08:38:57 PDT 2009   NO_QUERY   
1599983         4  2193578758  Tue Jun 16 08:38:57 PDT 2009   NO_QUERY   
1599984         4  2193578847  Tue Jun 16 08:38:57 PDT 2009   NO_QUERY   
1599985         4  2193578982  Tue Jun 16 08:38:58 PDT 2009   NO_QUERY   
1599986         4  2193579087  Tue Jun 16 08:38:58 PDT 2009   NO_QUERY   
1599987         4  2193579092  Tue Jun 16 08:38:58 PDT 2009   NO_QUERY   
1599988         4  2193579191  Tue Jun 16 08:38:59 PDT 2009   NO_QUERY   
1599989         4  2193579211  Tue Jun 16 08:38:59 PDT 2009   NO_QUERY   
1599990         4  2193579249  Tue Jun 16 08:38:59 PDT 2009   NO_QUERY   
1599991         4  2193579284  Tue Jun 16 08:38:59 PDT 2009   NO_QUERY   
1599992      

In [48]:
class RegexPreprocess(object):
   
    """Create a preprocessing module for a tweet or data structure of tweets.
    1) replace username, e.g., @crawles -> USERNAME
    2) replace http links -> URL
    3) replace repeated letters to two letters
    """
    
    user_pat = '(?<=^|(?<=[^a-zA-Z0-9-_\.]))@([A-Za-z]+[A-Za-z0-9]+)'
    http_pat = '(https?:\/\/(?:www\.|(?!www))[^\s\.]+\.[^\s]{2,}|www\.[^\s]+\.[^\s]{2,})'
    repeat_pat, repeat_repl = "(.)\\1\\1+",'\\1\\1'
    
    def __init__(self):
        pass
    
    def transform(self, X):
        is_pd_series = isinstance(X, pd.core.frame.Series)
        if not is_pd_series:
            pp_text = pd.Series(X)
        else:
            pp_text = X
        pp_text = pp_text.str.replace(pat = self.user_pat, repl = 'USERNAME')
        pp_text = pp_text.str.replace(pat = self.http_pat, repl = 'URL')
        pp_text.str.replace(pat = self.repeat_pat, repl = self.repeat_repl)
        return pp_text
        
    def fit(self, X, y=None):
        return self

#### Training and testing the model

In [51]:
sentiment_lr = Pipeline([('regex_preprocess', RegexPreprocess()),
                         ('count_vect', CountVectorizer(min_df = 100,
                                                        ngram_range = (1,1),
                                                        stop_words = 'english')), 
                         ('lr', LogisticRegression())])
sentiment_lr.fit(dftrain.text, dftrain.polarity)

Pipeline(steps=[('regex_preprocess', <__main__.RegexPreprocess object at 0x00000116EEC4B7F0>), ('count_vect', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, mi...ty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False))])

In [52]:
cv=CountVectorizer()
xtraintestcv=cv.fit_transform(["hi man how are you,you are cazy","i hope you are good"])
xtraintestcv.toarray()

array([[2, 1, 0, 1, 0, 1, 1, 2],
       [1, 0, 1, 0, 1, 0, 0, 1]], dtype=int64)

In [50]:
cv.get_feature_names()

['are', 'cazy', 'good', 'hi', 'hope', 'how', 'man', 'you']

In [53]:
Xtest, ytest = dftest.text[dftest.polarity!=2], dftest.polarity[dftest.polarity!=2]

#Xtest,ytest=dftest.text,dftest.polarity

print(classification_report(ytest,sentiment_lr.predict(Xtest)))

             precision    recall  f1-score   support

          0       0.86      0.81      0.83       177
          4       0.82      0.87      0.85       182

avg / total       0.84      0.84      0.84       359



In [54]:
import dill
f = open('twitter_sentiment_model.pkl','wb')
r = RegexPreprocess()
dill.dump(sentiment_lr, f)
f.close()

In [56]:
# test
f = open('twitter_sentiment_model.pkl','rb')
cl = dill.load(f)
#print(classification_report(ytest,cl.predict(Xtest)))

print(cl.predict_proba("Hello big beautiful world"))

print(cl.predict_proba("you are too bad man"))
f.close()

[[ 0.07064946  0.92935054]]
[[ 0.78401794  0.21598206]]
